src/App/urls.py
from django.contrib import admin

from django.urls import include, path
from GestorTemplates.views import home
from django.views.i18n import JavaScriptCatalog


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('jsi18n', JavaScriptCatalog.as_view(), name='js-catlog'),
    path('Evento/', include('Evento.urls', namespace='Evento')),
    path('Utilizadores/', include('Utilizadores.urls', namespace='Utilizadores')),
    path('GestorTemplates/', include('GestorTemplates.urls')),
    path('Recurso/', include('Recurso.urls')),
    path('Inscricao/', include('Inscricao.urls')),
    path('Feedback/', include('Feedback.urls')),
    path('notificacoes/', include('Notificacoes.urls')),

]

src/Evento/urls.py
from django.urls import path
from .views import home_view, eventos, create_logistic, meus_eventos, gerir, select_type, create_event, \
    eventos_gerir, equip_logistic, espaco_logistic, servico_logistic, submit_logistic, view_logisticas, \
    view_event, ajax_filter_type, ajax_filter_state, delete_event, edit_event, ajax_finalizar_logistica, \
    validar_evento, delete_logistica, edit_logistica, edit_espaco, edit_servico, edit_equipamento, \
    select_form, submeter_event, aceitar_event, view_my_event, recusar_evento, evento_insc, associar_insc, \
    associar_feedback, evento_feedback

app_name = 'Evento'

urlpatterns = [
    path('', home_view, name='homeview'),
    path('all/', eventos, name='eventos'),
    path('myevents/', meus_eventos, name='meus-eventos'),
    path('gerir/<int:event_id>', gerir, name='gerir'),
    path('gerir/', eventos_gerir, name='eventos-gerir'),
    path('new/', select_type, name='select_type'),
    path('new/form/<int:type_id>', select_form, name='select_form'),
    path('new/create/<int:type_id>/<int:type_evento>', create_event, name='create-event'),
    path('new/submit/<int:event_id>', submeter_event, name='submeter-event'),
    path('new/aceitar/<int:event_id>', aceitar_event, name='aceitar-event'),
    path('new2/<int:event_id>', create_logistic, name='create-event2'),
    path('new2/equip/<int:event_id>', equip_logistic, name='equip-logistic'),
    path('new2/espaco/<int:event_id>', espaco_logistic, name='espaco-logistic'),
    path('new2/servico/<int:event_id>', servico_logistic, name='servico-logistic'),
    path('new2/submit_logistic/<int:event_id>', submit_logistic, name='submit-logistic'),
    path('gerir/view-logistic/<int:event_id>', view_logisticas, name='view-logistic'),
    path('gerir/validar-evento/<int:event_id>', validar_evento, name='validar-evento'),
    path('gerir/recusar-evento/<int:event_id>', recusar_evento, name='recusar-evento'),
    path('view/<int:event_id>', view_event, name='view-event'),
    path('view-my/<int:event_id>', view_my_event, name='view-my-event'),
    path('ajax/', ajax_filter_type, name='ajax-filter-type'),
    path('ajax/state', ajax_filter_state, name='ajax-filter-state'),
    path('ajax/finalizar_logistica', ajax_finalizar_logistica, name='ajax-finalizar-logistica'),
    path('delete/<int:event_id>', delete_event, name='delete-event'),
    path('delete-logistica/<int:event_id>', delete_logistica, name='delete-logistica'),
    path('edit/<int:event_id>', edit_event, name='edit-event'),
    path('edit-logistica/<int:event_id>', edit_logistica, name='edit-logistica'),
    path('edit-espaco/<int:event_id>', edit_espaco, name='edit-espaco'),
    path('edit-espaco/<int:event_id>/<int:espaco_id>/<str:tipo>', edit_espaco, name='edit-espaco'),
    path('edit-servico/<int:event_id>', edit_servico, name='edit-servico'),
    path('edit-equipamento/<int:event_id>', edit_equipamento, name='edit-equipamento'),

    path('evento-insc/<int:event_id>', evento_insc, name='evento-insc'),
    path('evento-feed/<int:event_id>', evento_feedback, name='evento-feed'),
    path('associar-insc/<int:event_id>/<int:form_id>', associar_insc, name='associar-insc'),
    path('associar-feedback/<int:event_id>/<int:form_id>', associar_feedback, name='associar-feedback'),
]

src/Recurso/urls.py
from django.urls import path, include
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from .views import RecursoList, RecursoCreate, RecursoDelete
from Recurso.views import recursos, recursosv2, recurso_detail, recurso_delete, espacos, empresas, edificios, \
    unidadesorganicas, \
    equipamentos, servicos, servico_create, equipamento_create, espaco_create, equipamento_delete, servico_delete, \
    empresa_create, empresa_delete, edificio_create, edificio_delete, unidadeorganica_delete, unidadeorganica_create, \
    universidades, universidade_create, universidade_delete, campis, campus_delete, campus_create, espaco_delete, \
    servico_detail, equipamento_detail, empresa_detail, unidadeorganica_update, unidadeorganica_detail, \
    universidade_detail, campus_update, edificio_detail, espaco_detail, campus_detail, componentes, componente_delete, \
    componente_detail, componente_update, recurso_update, equipamento_update, servico_update, empresa_update, \
    edificio_update, \
    espaco_update, universidade_update, recurso_atribuir, recurso_atribuir_list, recurso_atribuir_cancelar \
    , recurso_ajax, recurso_ajax_detail, recursosv1

app_name = 'Recurso'

urlpatterns = [

    # RECURSO
    path('', recursos, name='recursos'),
    path('all/<int:my_id>/<str:tipo>/<int:log>', recursosv2, name='recursos-2'),
    path('all/<int:my_id>', recursosv1, name='recursos-1'),
    path('atribuir/<int:my_id>/<str:tipo>/<int:time>/<int:log>', recurso_atribuir_list, name='recurso-atribuir-list'),
    path('atribuir-2/<int:my_id>/<int:obj_id>/<int:time>/<int:log>', recurso_atribuir, name='recurso-atribuir'),
    path('atribuir-cancelar/<int:my_id>/<int:obj_id>/<int:log>/<str:tipo>', recurso_atribuir_cancelar,
         name='recurso-atribuir-cancelar'),
    path('recurso/<int:my_id>/detail/', recurso_detail, name='recurso-detail'),
    path('recurso/<int:my_id>/delete/', recurso_delete, name='recurso-delete'),
    path('recurso/<int:my_id>/', recurso_update, name='recurso-update'),

    # COMPONENTE
    path('componentes', componentes, name='componentes'),
    path('componentes/<int:my_id>/delete/', componente_delete, name='componente-delete'),
    path('componente/<int:my_id>/detail', componente_detail, name='componente-detail'),
    path('componente/<int:my_id>/', componente_update, name='componente-update'),

    # ESPAÇO
    # path('espaco', espacos, name='espacos'),
    path('espaco/espaco_create/', espaco_create, name='espaco-create'),
    path('espaco/<int:my_id>/delete/', espaco_delete, name='espaco-delete'),
    path('espaco/<int:my_id>/detail/', espaco_detail, name='espaco-detail'),
    path('espaco/<int:my_id>/', espaco_update, name='espaco-update'),

    # EQUIPAMENTOS
    # path('equip', equipamentos, name='equipamentos'),
    path('equip/equipamento_create/', equipamento_create, name='equipamento-create'),
    path('equip/<int:my_id>/delete/', equipamento_delete, name='equipamento-delete'),
    path('equip/<int:my_id>/detail/', equipamento_detail, name='equipamento-detail'),
    path('equip/<int:my_id>/', equipamento_update, name='equipamento-update'),

    # SERVIÇOS
    # path('servico', servicos, name='servicos'),
    path('servico/servico_create/', servico_create, name='servico-create'),
    path('servico/<int:my_id>/delete/', servico_delete, name='servico-delete'),
    path('servico/<int:my_id>/detail/', servico_detail, name='servico-detail'),
    path('servico/<int:my_id>/', servico_update, name='servico-update'),

    # EMPRESAS
    # path('empresa', empresas, name='empresas'),
    path('empresa/empresa_create/', empresa_create, name='empresa-create'),
    path('empresa/<int:my_id>/delete/', empresa_delete, name='empresa-delete'),
    path('empresa/<int:my_id>/detail/', empresa_detail, name='empresa-detail'),
    path('empresa/<int:my_id>/', empresa_update, name='empresa-update'),

    # EDIFICIOS
    # path('edificio', edificios, name='edificios'),
    path('edificio/edificio_create/', edificio_create, name='edificio-create'),
    path('edificio/<int:my_id>/delete/', edificio_delete, name='edificio-delete'),
    path('edificio/<int:my_id>/detail/', edificio_detail, name='edificio-detail'),
    path('edificio/<int:my_id>/', edificio_update, name='edificio-update'),

    # UNIDADE ORGANICA
    # path('unidade-organica', unidadesorganicas, name='unidades-organicas'),
    path('unidade-organica/unidade-organica_create/', unidadeorganica_create, name='unidade-organica-create'),
    path('unidade-organica/<int:my_id>/delete/', unidadeorganica_delete, name='unidade-organica-delete'),
    path('unidade-organica/<int:my_id>/detail/', unidadeorganica_detail, name='unidade-organica-detail'),
    path('unidade-organica/<int:my_id>/', unidadeorganica_update, name='unidade-organica-update'),

    # UNIVERSIDADE
    # path('universidade', universidades, name='universidades'),
    path('universidade/universidade_create/', universidade_create, name='universidade-create'),
    path('universidade/<int:my_id>/delete/', universidade_delete, name='universidade-delete'),
    path('universidade/<int:my_id>/detail/', universidade_detail, name='universidade-detail'),
    path('universidade/<int:my_id>/', universidade_update, name='universidade-update'),

    # CAMPUS
    # path('campus', campis, name='campis'),
    path('campus/campus_create/', campus_create, name='campus-create'),
    path('campus/<int:my_id>/delete/', campus_delete, name='campus-delete'),
    path('campus/<int:my_id>/detail/', campus_detail, name='campus-detail'),
    path('campus/<int:my_id>/', campus_update, name='campus-update'),

    # AJAX
    path('ajax/', recurso_ajax, name='recurso-ajax'),
    path('ajax_detail/', recurso_ajax_detail, name='recurso-ajax-detail'),
]

src/Recurso/forms.py
from django import forms

from .models import Recurso, Espaco, Equipamento, Servico, Empresa, Edificio, Unidadeorganica, Universidade, Campus
from django.core.exceptions import NON_FIELD_ERRORS


class RecursoForm(forms.ModelForm):
    class Meta:
        model = Recurso
        fields = [
            'Nome',
            'fonte',
            'empresaid',

        ]
        widget = forms.TextInput(attrs={'class': "input-clean"})


class EspacoForm(forms.ModelForm):
    class Meta:
        model = Espaco
        fields = [
            'Nome',
            'tipo',
            'capacidade',
            'mobilidade',
            'edificioid'
        ]
        widgets = {
            'Nome': forms.TextInput(attrs={'class': "input-clean"}),
            'tipo': forms.TextInput(attrs={'class': "input-clean"}),
            'capacidade': forms.TextInput(attrs={'class': "input-clean"}),
        }
        error_messages = {
            NON_FIELD_ERRORS: {
                'unique_together': "Já existe um Espaço com este nome no Edifício selecionado",
            },
            'capacidade': {
                'invalid': 'A capacidade tem que ser um número inteiro positivo'
            }
        }


class EquipamentoForm(forms.ModelForm):
    class Meta:
        model = Equipamento
        fields = [
            'Nome',
            'descricao',
            'unidadeorganicaid',
            'espacoid',
        ]
        widgets = {
            'Nome': forms.TextInput(attrs={'class': "input-clean"}),
            'descricao': forms.TextInput(attrs={'class': "input-clean"}),
        }
        error_messages = {
            'Nome': {
                "unique": "O nome selecionado já foi atribuído a outro equipamento",
            },
            'descricao': {
            },
        }


class ServicoForm(forms.ModelForm):
    class Meta:
        model = Servico
        fields = [
            'Nome',
            'Descricao',
            'unidadeorganicaid',
        ]
        widgets = {
            'Nome': forms.TextInput(attrs={'class': "input-clean"}),
            'Descricao': forms.TextInput(attrs={'class': "input-clean"}),
        }
        error_messages = {
            'Nome': {
                "unique": "O nome para este serviço já foi atribuído a outro serviço",
            },
            'Descricao': {
            },
        }


class EmpresaForm(forms.ModelForm):
    class Meta:
        model = Empresa
        fields = [
            'Nome',
            'descricao',
            'email',
            'telefone',
            'cidade',
            'endereco',
            'codigopostal',
            'faturacao'
        ]
        widgets = {
            'Nome': forms.TextInput(attrs={'class': "input-clean"}),
            'descricao': forms.TextInput(attrs={'class': "input-clean"}),
            'email': forms.TextInput(attrs={'class': "input-clean"}),
            'telefone': forms.TextInput(attrs={'class': "input-clean"}),
            'cidade': forms.TextInput(attrs={'class': "input-clean"}),
            'endereco': forms.TextInput(attrs={'class': "input-clean"}),
            'codigopostal': forms.TextInput(attrs={'class': "input-clean"}),
            'faturacao': forms.TextInput(attrs={'class': "input-clean"}),
        }
        error_messages = {
            'Nome': {
                'unique': "Já existe uma Empresa com este nome",
            },
            'email': {
                'invalid': "O endereço de email introduzido é inválido"
            },
            'telefone': {
                'invalid': "O número de telefone introduzido é inválido"
            },
            'codigopostal': {
                'invalid': "O código postal introduzido é inválido, deve ter o formato XXXX-XXX"
            },
            'faturacao': {
                'invalid': "O Número de Contribuinte introduzido é inválido"
            },
            'endereco': {
                'invalid': "O Endereço introduzido é inválido"
            },

        }


class EdificioForm(forms.ModelForm):
    class Meta:
        model = Edificio
        fields = [
            'Nome',
            'localizacao',
            'campusid'
        ]
        widgets = {
            'Nome': forms.TextInput(attrs={'class': "input-clean"}),
            'localizacao': forms.TextInput(attrs={'class': "input-clean"}),
        }
        error_messages = {
            NON_FIELD_ERRORS: {
                'unique_together': "Já existe um Edifício com este nome no Campus selecionado",
            }
        }


class UnidadeOrganicaForm(forms.ModelForm):
    class Meta:
        model = Unidadeorganica
        fields = [
            'Nome',
            'universidadeid'
        ]
        widgets = {
            'Nome': forms.TextInput(attrs={'class': "input-clean"}),
        }
        error_messages = {
            NON_FIELD_ERRORS: {
                'unique_together': "Já existe uma Unidade Orgânica com este nome na Universidade selecionada",
            }
        }


class UniversidadeForm(forms.ModelForm):
    class Meta:
        model = Universidade
        fields = [
            'Nome',
            'localizacao'
        ]
        widgets = {
            'Nome': forms.TextInput(attrs={'class': "input-clean"}),
            'localizacao': forms.TextInput(attrs={'class': "input-clean"}),
        }


class CampusForm(forms.ModelForm):
    class Meta:
        model = Campus
        fields = [
            'Nome',
            'universidadeid'
        ]
        widgets = {
            'Nome': forms.TextInput(attrs={'class': "input-clean"}),
        }
        error_messages = {
            NON_FIELD_ERRORS: {
                'unique_together': "Já existe um Campus com este nome na Universidade selecionada",
            }
        }

src/templates/Recurso/edificio_detail.html
{% extends 'app.html' %}

{% block title %}- Página Inicial{% endblock title %}

{% block content %}
    {% load static %}

    <div>
        <div class="section">
            <nav class="breadcrumb has-bullet-separator is-medium" aria-label="breadcrumbs">
                        <ul>
                            <li><a href="{% url 'home' %}">Página inicial</a></li>
                            <li><a href="{% url 'Recurso:componentes' %}">Componentes</a></li>
                            <li class="is-active">
                                <a href="#" aria-current="page">
                                            <span class="has-text-weight-bold">
                                                Edifício
                                            </span>
                                </a>
                            </li>
                        </ul>
                    </nav>
            <div class="columns is-align-items-center">
                <div class="column">
                    <h1 class="title has-text-centered">{{ obj.Nome }}</h1>
                    <div class="event-group">
                        <span class="span-header">Campus:</span>
                        <p class="event-body long-text">{{ obj.campusid }} </p>
                    </div>
                </div>
            </div>
                                <div class="control">
                        <a class="button is-link" href="{% url 'Recurso:componentes' %}"> Voltar
                            atrás </a>
                    </div>
        </div>
    </div>

{% endblock content %}

src/templates/Recurso/equip_detail.html
{% extends 'app.html' %}

{% block title %}- Página Inicial{% endblock title %}

{% block content %}
    {% load static %}

    <div>
        <div class="section">
        <nav class="breadcrumb has-bullet-separator is-medium" aria-label="breadcrumbs">
                        <ul>
                            <li><a href="{% url 'home' %}">Página inicial</a></li>
                            <li><a href="{% url 'Recurso:componentes' %}">Componentes</a></li>
                            <li class="is-active">
                                <a href="#" aria-current="page">
                                            <span class="has-text-weight-bold">
                                                Equipamento
                                            </span>
                                </a>
                            </li>
                        </ul>
                    </nav>
            <div class="columns is-align-items-center">
                <div class="column">
                    <h1 class="title has-text-centered">{{ obj.Nome }}</h1>
                    <div class="event-group">
                        <span class="span-header">Descrição:</span>
                        <p class="event-body long-text">{{ obj.descricao }} </p>
                    </div>
                    <div class="event-group">
                        <span class="span-header">Unidade Orgânica:</span>
                        {% if obj.unidadeorganicaid is not None %}
                        <p class="event-body long-text">{{ obj.unidadeorganicaid }} </p>
                        {% else %}
                        <p class="event-body long-text">--------</p>
                        {% endif %}
                    </div>
                    <div class="event-group">
                        <span class="span-header">Espaço:</span>
                        {% if obj.espacoid is not None %}
                        <p class="event-body long-text">{{ obj.espacoid }} </p>
                        {% else %}
                        <p class="event-body long-text">--------</p>
                        {% endif %}
                    </div>
                </div>
            </div>
                            <div class="control">
                        <a class="button is-link" href="{% url 'Recurso:recursos' %}"> Voltar
                            atrás </a>
                    </div>
        </div>
    </div>

{% endblock content %}

src/templates/Recurso/espaco_detail.html
{% extends 'app.html' %}

{% block title %}- Página Inicial{% endblock title %}

{% block content %}
    {% load static %}

    <div>
        <div class="section">
        <nav class="breadcrumb has-bullet-separator is-medium" aria-label="breadcrumbs">
                        <ul>
                            <li><a href="{% url 'home' %}">Página inicial</a></li>
                            <li><a href="{% url 'Recurso:componentes' %}">Componentes</a></li>
                            <li class="is-active">
                                <a href="#" aria-current="page">
                                            <span class="has-text-weight-bold">
                                                Espaço
                                            </span>
                                </a>
                            </li>
                        </ul>
                    </nav>
            <div class="columns is-align-items-center">
                <div class="column">
                    <h1 class="title has-text-centered">{{ obj.Nome }}</h1>
                    <div class="event-group">
                        <span class="span-header">Tipo:</span>
                        <p class="event-body long-text">{{ obj.tipo }} </p>
                    </div>
                    <div class="event-group">
                        <span class="span-header">Capacidade:</span>
                        <p class="event-body long-text">{{ obj.capacidade }} </p>
                    </div>
                    <div class="event-group">
                        <span class="span-header">Mobilidade:</span>
                        {% if obj.edificioid is True %}
                            <p class="event-body long-text">Sim</p>
                        {% else %}
                            <p class="event-body long-text">Não</p>
                        {% endif %}
                    </div>
                    <div class="event-group">
                        <span class="span-header">Edifício:</span>
                        {% if obj.edificioid is not None %}
                            <p class="event-body long-text">{{ obj.edificioid }} </p>
                        {% else %}
                            <p class="event-body long-text">--------</p>
                        {% endif %}
                    </div>
                </div>
            </div>
                            <div class="control">
                        <a class="button is-link" href="{% url 'Recurso:recursos' %}"> Voltar
                            atrás </a>
                    </div>
        </div>
    </div>

{% endblock content %}

src/templates/Recurso/recurso_atribuir.html
{% extends 'app.html' %}


{% block title %}- Página Inicial{% endblock title %}


{% block page_css %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/dataTables.bulma.min.css">

{% endblock %}
{% block content %}
    {% load static %}
    <div class="column">
        <nav class="breadcrumb has-bullet-separator is-medium" aria-label="breadcrumbs">
          <ul>
              <li> <a href="{% url 'Evento:eventos-gerir'  %}">Gerir eventos</a> </li>
              <li> <a href="{% url 'Evento:gerir' evento.id  %}">{{evento.nome}}</a> </li>
              <li> <a href="{% url 'Evento:view-logistic' evento.id  %}">Pedido da logística</a> </li>
            <li class="is-active">
              <a href="#" aria-current="page">
                <span class="has-text-weight-bold">Atribuir recurso</span>
              </a>
            </li>
          </ul>
        </nav>
      </div>  

    <div>
        <section id="subnavbar">
            <nav class="" role="navigation" aria-label="main navigation">
                <div class="navbar-brand">
                    <a role="button" class="navbar-burger burger"
                       onclick="$('#form-menu-buttons').toggleClass('is-active')">
                        <span aria-hidden="true"></span>
                        <span aria-hidden="true"></span>
                        <span aria-hidden="true"></span>
                    </a>
                </div>
                <div class="navbar-menu is-white" id="form-menu-buttons">
                    <div class="navbar-start">
                        <!-- navbar items on the left side -->
                        <div class="column">
                            <nav class="breadcrumb has-bullet-separator is-medium" aria-label="breadcrumbs">
                                <ul>
                                    <li class="is-active">
                                        <a href="#" aria-current="page">
                                            <span class="has-text-weight-bold">Atribuir Recurso - {{evento.nome}}</span>
                                        </a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </div>

                </div>
            </nav>

        </section>

        <div class="section" id="main-section-content">
            <div class="columns">
                <div class="column ">

                    <table id="form-list-table" class="table is-fullwidth is-striped is-hoverable" style="width:100%">
                        <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Tipo</th>
                            <th>Fonte</th>
                            <th>Empresa</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for obj in rec %}
                            <tr class="datatable-row datatable-selector" data-id="{{ obj.id }}">
                                <td class="td">{{ obj.Nome }}</td>
                                {% if obj.espacoid is not None %}
                                    <td class="td"> Espaço</td>
                                {% elif obj.equipamentoid.Nome is not None %}
                                    <td class="td"> Equipamento</td>
                                {% elif obj.servicoid.Nome is not None %}
                                    <td class="td"> Serviço</td>
                                {% endif %}
                                <td class="td"> {{ obj.fonte }}</td>
                                {% if obj.empresaid is not None %}
                                    <td class="td"> {{ obj.empresaid }}</td>
                                {% else %}
                                    <td class="td"> --------</td>
                                {% endif %}
                                <td>
                                    <a href="#" class="button btn-atribuir"
                                            data-logisticaid="{{logistica.id}}"
                                            data-id="{{ obj.id }}"
                                            >
                                            Atribuir
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>


    </div>

    </div>




{% endblock content %}

{% block scripts %}

    <script type="text/javascript" src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.24/js/dataTables.bulma.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bulma-accordion@2.0.1/dist/js/bulma-accordion.min.js"></script>
    <script>

       


        //DATATABLES MANIPULATION
        $(document).ready(function () {
            var table = $('#form-list-table').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.24/i18n/Portuguese.json"
                },
                "columnDefs": [{"orderable": false, "targets": 4},
                    {
                        "targets": [0],
                        "visible": true
                    }
                ],
            });
            //tabs filters
            let tabs = $('.tabs li')
            tabs.click(function () {
                tabs.removeClass('is-active')
                $(this).addClass('is-active');
                table.column($(this).data('column'))
                    .search($(this).data('filter'))
                    .draw();
            })
        });


        $('.datatable-row').click(function () {
            let url = "{% url 'Recurso:recurso-detail' my_id=123  %}"
            location.href = url.replace('123', $(this).data('id'))
        });

        $('#close-message').click(function () {
            let message = $('#close-message').parent().parent();
            message.addClass('is-hidden')
        });

        $('.button-edit').click(function (e) {
            e.stopPropagation();
            let url = "{% url 'Recurso:recurso-update' my_id=123  %}"
            location.href = url.replace('123', $(this).data('id'))
        });



        //Listen to atribuir 
        const attrBtns = document.querySelectorAll('.btn-atribuir');
        console.log(attrBtns);

        attrBtns.forEach(btn => {
            btn.addEventListener('click', function(e) {
                e.preventDefault();
                e.stopPropagation();
                const evento_id = "{{evento.id}}";
                const obj_id = e.target.dataset.id;
                const hora = "{{hora.id}}"
                const logisticaid = e.target.dataset.logisticaid;

                let url = "{% url 'Recurso:recurso-atribuir' my_id=123 obj_id=456 time=789 log=999%}"
                url = url.replace('456', obj_id)
                url = url.replace('789', hora)
                url = url.replace('999', logisticaid)
                location.href = url.replace('123', evento_id)
                
            })
        })


    </script>
{% endblock %}

src/templates/Recurso/servico_detail.html
{% extends 'app.html' %}

{% block title %}- Página Inicial{% endblock title %}

{% block content %}
    {% load static %}

    <div>
        <div class="section">
        <nav class="breadcrumb has-bullet-separator is-medium" aria-label="breadcrumbs">
                        <ul>
                            <li><a href="{% url 'home' %}">Página inicial</a></li>
                            <li><a href="{% url 'Recurso:componentes' %}">Componentes</a></li>
                            <li class="is-active">
                                <a href="#" aria-current="page">
                                            <span class="has-text-weight-bold">
                                                Serviço
                                            </span>
                                </a>
                            </li>
                        </ul>
                    </nav>
            <div class="columns is-align-items-center">
                <div class="column">
                    <h1 class="title has-text-centered">{{ obj.Nome }}</h1>
                    <div class="event-group">
                        <span class="span-header">Descrição:</span>
                        <p class="event-body long-text">{{ obj.Descricao }} </p>
                    </div>
                    <div class="event-group">
                        <span class="span-header">Unidade Orgânica:</span>
                        {% if obj.unidadeorganicaid is not None %}
                            <p class="event-body long-text">{{ obj.unidadeorganicaid }} </p>
                        {% else %}
                            <p class="event-body long-text">--------</p>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="control">
                <a class="button is-link" href="{% url 'Recurso:recursos' %}"> Voltar
                    atrás </a>
            </div>
        </div>
    </div>

{% endblock content %}