src/App/urls.py
from django.contrib import admin

from django.urls import include, path
from GestorTemplates.views import home
from django.views.i18n import JavaScriptCatalog


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('jsi18n', JavaScriptCatalog.as_view(), name='js-catlog'),
    path('Evento/', include('Evento.urls', namespace='Evento')),
    path('Utilizadores/', include('Utilizadores.urls', namespace='Utilizadores')),
    path('GestorTemplates/', include('GestorTemplates.urls')),
    path('Recurso/', include('Recurso.urls')),
    path('Inscricao/', include('Inscricao.urls')),
    path('Feedback/', include('Feedback.urls')),
    path('notificacoes/', include('Notificacoes.urls')),

]

src/Utilizadores/urls.py
from django.urls import path
from .views import registar, login, logout_view


app_name = 'Utilizadores'


urlpatterns = [
    path('registar/', registar, name='registar'),
    path('login/', login, name='login'),
    path('logout/', logout_view, name='logout'),
]       

src/Utilizadores/utilizadores_old/urls.py
from django.urls import path, include
from .views import consultar_utilizadores
from .views import escolher_perfil
from .views import criar_utilizador
from .views import apagar_utilizador
from .views import alterar_utilizador
from .views import concluir_registo
from .views import home
from .views import login_action
from .views import logout_action
from .views import mensagem
from .views import alterar_password

from . import views

app_name = 'utilizadores'


urlpatterns = [
    path('consultarutilizadores', consultar_utilizadores.as_view(),name='consultar-utilizadores'),
    path('escolherperfil', escolher_perfil,name='escolher-perfil'),    
    path('criarutilizadores/<int:id>', criar_utilizador, name='criar-utilizador'),
    path('alterarpassword',alterar_password,name='alterar-password'),

    path('apagarproprioutilizador', views.apagar_proprio_utilizador,name='apagar-conta'),
    path('apagarutilizador/<int:id>', views.apagar_utilizador,name='apagar-utilizador'),
    path('alterarutilizadoradmin/<int:id>', views.alterar_utilizador_admin,name='alterar-utilizador-admin'),
    path('alterarutilizador', views.alterar_utilizador,name='alterar-utilizador'),
    path('validarutilizador/<int:id>', views.validar_utilizador,name='validar-utilizador'),
    path('rejeitarutilizador/<int:id>', views.rejeitar_utilizador,name='rejeitar-utilizador'),
    path('alteraridioma', views.alterar_idioma,name='alterar-idioma'),


    path('concluirregisto/<int:id>', concluir_registo,name='concluir-registo'),
    path('mensagem/<int:id>', mensagem,name='mensagem'),
    path('validar/<str:nome>/<int:id>', views.enviar_email_validar,name='validar'),
    path('rejeitar/<str:nome>/<int:id>', views.enviar_email_rejeitar,name='rejeitar'),
    path("logout", logout_action, name="logout"), 
    path("login", login_action, name="login"),   

    
    path('mudarperfilescolha/<int:id>', views.mudar_perfil_escolha_admin,name='mudar-perfil-escolha-admin'),    
    path('mudarperfil/<int:tipo>/<int:id>', views.mudar_perfil_admin, name='mudar-perfil-admin'),

    path('mudarmeuperfilescolha', views.mudar_perfil_escolha,name='mudar-perfil-escolha'),    
    path('mudarmeuperfil/<int:tipo>', views.mudar_perfil, name='mudar-perfil'),

    path('ajax/load-departamentos/', views.load_departamentos, name='ajax_load_departamentos'),
    path('ajax/load-cursos/', views.load_cursos, name='ajax_load_cursos'),

]       

src/Utilizadores/models.py
from django.db import models


# Create your models here.


class Admin(models.Model):
    id = models.AutoField(db_column='Id', primary_key=True)  # Field name made lowercase.
    gabinete = models.CharField(db_column='Gabinete', max_length=255, blank=True,
                                null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Admin'


class Gcp(models.Model):
    id = models.AutoField(db_column='id', primary_key=True)  # Field name made lowercase.

    class Meta:
        managed = True
        db_table = 'GCP'


    def __str__(self):
        return str(self.id)


class ProponenteExterno(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    profissao = models.CharField(max_length=255, blank=True, null=True)
    empresa = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'Proponente Externo'


class ProponenteInterno(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    numeroualg = models.IntegerField(db_column='numeroUALG', blank=True, null=True)  # Field name made lowercase.
    curso = models.CharField(max_length=255, blank=True, null=True)
    profissao = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'Proponente interno'


class Servicostecnicos(models.Model):
    class Meta:
        managed = False
        db_table = 'ServicosTecnicos'


class User(models.Model):
    id = models.AutoField(db_column='Id', primary_key=True)  # Field name made lowercase.
    password = models.CharField(db_column='Password', max_length=255, blank=True,
                                null=True)  # Field name made lowercase.
    last_login = models.DateTimeField(db_column='Last_login', blank=True, null=True)  # Field name made lowercase.
    is_superuser = models.IntegerField(blank=True, null=True)
    username = models.CharField(max_length=255, default='')
    first_name = models.CharField(max_length=255, blank=True, null=True)
    last_name = models.CharField(max_length=255, blank=True, null=True)
    email = models.CharField(max_length=255, blank=True, null=True)
    is_active = models.IntegerField(blank=True, null=True)
    date_joined = models.DateTimeField(blank=True, null=True)
    morada = models.CharField(max_length=255, blank=True, null=True)
    contribuinte = models.IntegerField(blank=True, null=True)
    datanascimento = models.DateTimeField(db_column='dataNascimento', blank=True,
                                          null=True)  # Field name made lowercase.
    adminid = models.ForeignKey(Admin, models.DO_NOTHING, db_column='AdminId', blank=True,
                                null=True)  # Field name made lowercase.
    gcpid = models.ForeignKey(Gcp, models.DO_NOTHING, db_column='GCPid', blank=True,
                              null=True)  # Field name made lowercase.
    proponente_externoid = models.ForeignKey(ProponenteExterno, models.DO_NOTHING,
                                             db_column='Proponente Externoid', blank=True,
                                             null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    proponente_internoid = models.ForeignKey(ProponenteInterno, models.DO_NOTHING,
                                             db_column='Proponente internoID', blank=True,
                                             null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    servicostecnicosid = models.ForeignKey(Servicostecnicos, models.DO_NOTHING,
                                           db_column='ServicosTecnicosid', blank=True,
                                           null=True)  # Field name made lowercase.

    class Meta:
        managed = True
        db_table = 'User'
    
    def __str__(self):
        return self.username

src/Utilizadores/utilizadores_old/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from atividades import models as amodels
from colaboradores.models import ColaboradorHorario,PreferenciaAtividade,Preferencia
from coordenadores import models as coordmodels
from django.db.models import Q
from datetime import datetime,timedelta
class Utilizador(User):
    contacto = PhoneNumberField(max_length=20, blank=False, null=False)
    valido = models.CharField(max_length=255, blank=False, null=False)

    def getProfiles(self):
        type = ''
        if Administrador.objects.filter(utilizador_ptr_id=self):
            type = self.concat(type=type, string='Administrador')
        if Participante.objects.filter(utilizador_ptr_id=self):
            type = self.concat(type=type, string='Participante')
        if ProfessorUniversitario.objects.filter(utilizador_ptr_id=self):
            type = self.concat(type=type, string='ProfessorUniversitario')
        if Coordenador.objects.filter(utilizador_ptr_id=self):
            type = self.concat(type=type, string='Coordenador')
        if Colaborador.objects.filter(utilizador_ptr_id=self):
            type = self.concat(type=type, string='Colaborador')
        return type

    def concat(self, type, string):
        if type == '':
            type = string
        else:
            type += ', '+string
        return type

    @property
    def firstProfile(self):
        return self.getProfiles().split(' ')[0]

    def getUser(self):
        user = User.objects.get(id=self.id)
        if user.groups.filter(name = "Coordenador").exists():
            result = Coordenador.objects.get(id=self.id)
        elif user.groups.filter(name = "Administrador").exists():
            result = Administrador.objects.get(id=self.id)
        elif user.groups.filter(name = "ProfessorUniversitario").exists():
            result = ProfessorUniversitario.objects.get(id=self.id)
        elif user.groups.filter(name = "Colaborador").exists():
            result = Colaborador.objects.get(id=self.id)
        elif user.groups.filter(name = "Participante").exists():
            result = Participante.objects.get(id=self.id)
        else:
            result = None
        return result   


    def getProfile(self):
        user = User.objects.get(id=self.id)
        if user.groups.filter(name = "Coordenador").exists():
            result = "Coordenador"
        elif user.groups.filter(name = "Administrador").exists():
            result = "Administrador"
        elif user.groups.filter(name = "ProfessorUniversitario").exists():
            result = "ProfessorUniversitario"
        elif user.groups.filter(name = "Colaborador").exists():
            result = "Colaborador"
        elif user.groups.filter(name = "Participante").exists():
            result = "Participante"
        else:
            result = None
        return result 

    def emailValidoUO(self,uo):
        user = User.objects.get(email=self.email)
        if user.groups.filter(name = "Coordenador").exists():
            utilizador = Coordenador.objects.get(email=self.email)
        elif user.groups.filter(name = "Administrador").exists():
            return True
        elif user.groups.filter(name = "ProfessorUniversitario").exists():
            utilizador = ProfessorUniversitario.objects.get(email=self.email)
        elif user.groups.filter(name = "Colaborador").exists():
            utilizador = Colaborador.objects.get(email=self.email)
        else:
            return False
        if utilizador.faculdade == uo:
            return True
        else:
            return False   

    def emailValidoParticipante(self):
        user = User.objects.get(email=self.email)
        if user.groups.filter(name = "Administrador").exists():
            return True
        else:
            return False    
    @property
    def full_name(self):
        return self.first_name + ' ' + self.last_name
    class Meta:
        db_table = 'Utilizador'


class Administrador(Utilizador):
    gabinete = models.CharField(max_length=255, blank=False, null=False)

    class Meta:
        db_table = 'Administrador'


class Participante(Utilizador):
    class Meta:
        db_table = 'Participante'


class ProfessorUniversitario(Utilizador):
    gabinete = models.CharField(
        db_column='Gabinete', max_length=255, blank=False, null=False)

    faculdade = models.ForeignKey(
        'configuracao.Unidadeorganica', models.CASCADE)

    departamento = models.ForeignKey(
        'configuracao.Departamento', models.CASCADE)

    def __str__(self):
        return str(self.gabinete) + ' ' + str(self.faculdade) + ' ' + str(self.departamento)
    class Meta:
        db_table = 'ProfessorUniversitario'


class Coordenador(Utilizador):
    gabinete = models.CharField(
        db_column='Gabinete', max_length=255, blank=False, null=False)

    faculdade = models.ForeignKey(
        'configuracao.Unidadeorganica', models.CASCADE, db_column='FaculdadeID')

    departamento = models.ForeignKey(
        'configuracao.Departamento', models.CASCADE, db_column='DepartamentoID')

    class Meta:
        db_table = 'Coordenador'

    def __str__(self):
        return self.first_name


class Colaborador(Utilizador):
    curso = models.ForeignKey(
        'configuracao.Curso', models.CASCADE)

    faculdade = models.ForeignKey(
        'configuracao.Unidadeorganica', models.CASCADE)

    departamento = models.ForeignKey(
        'configuracao.Departamento', models.CASCADE)

    class Meta:
        db_table = 'Colaborador'

    @staticmethod
    def get_free_colabs(coord,dia,horario,tipo,sessao=None):
        free_colabs=[]
        colabs = Colaborador.objects.filter(faculdade = coord.faculdade,utilizador_ptr_id__valido=True)
        free = True
        for colab in colabs: 
            tarefas = coordmodels.Tarefa.objects.filter(colab = colab.id,horario=horario,dia=dia)

            if tarefas.exists():
                continue

            if not ColaboradorHorario.objects.filter(colab=colab.id).exists():
                continue

            elif sessao is not None and (Preferencia.objects.filter(colab = colab.id, tipoTarefa='tarefaAuxiliar').exists() or not Preferencia.objects.filter(colab = colab.id).exists()):
                s = amodels.Sessao.objects.get(id=int(sessao))
                inicio = s.horarioid.inicio
                fim = s.horarioid.fim
                
                if not ColaboradorHorario.objects.filter(colab = colab.id,dia=dia)\
                    .filter(inicio__lte=horario,fim__gte=horario).exists(): 
                    continue

                if coordmodels.Tarefa.objects.filter(colab = colab.id,dia=dia,horario__gt=inicio).filter(horario__lt=fim).exists(): 
                    continue
                if coordmodels.TarefaAuxiliar.objects.filter(tarefaid__colab = colab.id,tarefaid__dia=dia,sessao__horarioid__inicio__lt=inicio,sessao__horarioid__fim__gt=inicio).exists():
                    continue
                if PreferenciaAtividade.objects.filter(preferencia__colab=colab.id).exists() and not PreferenciaAtividade.objects.filter(preferencia__colab=colab.id,atividade = s.atividadeid.id).exists():
                    continue

                tarefas = coordmodels.Tarefa.objects.filter(colab = colab.id,dia=dia)

                for t in tarefas:
                    hinicio = datetime.strptime(str(inicio),'%H:%M:%S') 
                    hfim =   datetime.strptime(str(fim),'%H:%M:%S')  
                    if t.tipo != 'tarefaAuxiliar' and (datetime.strptime(str(t.horario),'%H:%M:%S') - hinicio >  timedelta(hours=0,minutes=15,seconds=0) or hfim - datetime.strptime(str(t.horario),'%H:%M:%S') < timedelta(days=-1,hours=23,minutes=45)) :
                        free=False     
                if free == True:
                    free_colabs.append(colab)
            elif sessao is None:
                
                if not Preferencia.objects.filter(colab = colab.id, tipoTarefa=tipo).exists():
                    continue
                
                free=True
                tarefas = coordmodels.Tarefa.objects.filter(colab = colab.id,dia=dia)

                for t in tarefas:
                    if len(horario) == 5:
                        h = datetime.strptime(horario,'%H:%M')
                    if len(horario)==8:
                        h = datetime.strptime(horario,'%H:%M:%S')
                    if datetime.strptime(str(t.horario),'%H:%M:%S') - h >  timedelta(days=-1,hours=23,minutes=45) and h - datetime.strptime(str(t.horario),'%H:%M:%S') <  timedelta(minutes=15):
                        free=False     
                if coordmodels.TarefaAuxiliar.objects.filter(tarefaid__colab = colab.id,tarefaid__dia=dia)\
                    .filter(sessao__horarioid__inicio__lte=horario,sessao__horarioid__fim__gte=horario).exists(): 
                    continue
                if not ColaboradorHorario.objects.filter(colab = colab.id,dia=dia)\
                    .filter(inicio__lte=horario,fim__gte=horario).exists(): 
                    continue
                if free == True:
                    free_colabs.append(colab)
        return free_colabs



    def get_horarios_disponiveis(self):
        return ColaboradorHorario.objects.filter(colab=self.id)

    def get_preferencia_atividade(self):
        horarios = self.get_horarios_disponiveis()
        atividades = []
        for horario in horarios:
            sessoes= amodels.Sessao.objects.filter(horarioid__fim__gte=horario.inicio,horarioid__fim__lte=horario.fim,atividadeid__estado="Aceite",atividadeid__professoruniversitarioutilizadorid__faculdade=self.faculdade, dia=horario.dia)
        
        for sessao in sessoes:
            atividades.append(sessao.atividadeid)

src/Utilizadores/templates/utilizadores/alterar_utilizador_admin.html
{% extends 'app.html' %}



{% block title %}- Alterar Utilizador {{nome}} {% endblock title %}


{% block content %}

<div>





  {% if registo == 1 or registo == 5 %}
  <form method="post">
    {% csrf_token %}
    {% elif registo == 2  %}
    <form method="post" id="ProfessorUniversitarioRegisterForm"
      data-departamentos-url="{% url 'utilizadores:ajax_load_departamentos' %}" novalidate>
      {% csrf_token %}
      {% elif registo == 3  %}
      <form method="post" id="CoordenadorRegisterForm"
        data-departamentos-url="{% url 'utilizadores:ajax_load_departamentos' %}" novalidate>
        {% csrf_token %}
        {% elif registo == 4  %}
        <form method="post" id="ColaboradorRegisterForm"
          data-departamentos-url="{% url 'utilizadores:ajax_load_departamentos' %}"
          data-cursos-url="{% url 'utilizadores:ajax_load_cursos' %}" novalidate>
          {% csrf_token %}
          {% endif %}

          <div style="padding: 1rem 2vw 0px;">
            <nav class="breadcrumb" aria-label="breadcrumbs">
              <ul>
                <li><a href="{% url 'home' %}">Início</a></li>
                <li class="is-active"><a href="{% url 'utilizadores:consultar-utilizadores' %}"
                    aria-current="page">Alterar Perfil</a></li>
              </ul>
            </nav>
            <div class="table ">
              <hr>
              <h2 class="title has-text-grey is-uppercase" style="font-size: 0.9rem;">
                {{perfil}}
              </h2>
              <div class="columns">
                <div class="column">
                  <div class="field">
                    <label class="label">Nome Próprio</label>
                    <div class="control is-clearfix">
                      <input name="first_name" class="input" id="id_first_name"
                        value="{{form.first_name.value|default_if_none:"" }}" style="" type="text" maxlength="255">
                      <!---->
                      <!---->
                      <!---->
                    </div>
                    <!---->
                  </div>
                </div>
                <div class="column">
                  <div class="field">
                    <label class="label">Apelido</label>
                    <div class="control is-clearfix">


                      <input name="last_name" class="input" id="id_last_name" style=""
                        value="{{form.last_name.value|default_if_none:"" }}" type="text" maxlength="255">
                    </div>
                    <!---->
                  </div>
                </div>

                <hr>
              </div>


              <div class="columns">

                <div class="column">
                  <div class="field">
                    <label class="label">Email</label>
                    <div class="control is-clearfix">
                      <input class="input" name="email" id="id_email" value="{{form.email.value|default_if_none:"" }}"
                        type="text" style="" maxlength="255">
                      <!---->
                      <!---->
                      <!---->
                    </div>
                    <!---->
                  </div>
                </div>
                <div class="column">
                  <div class="field">
                    <label class="label">Contacto</label>
                    <div class="control is-clearfix">

                      <input name="contacto" class="input" id="id_contacto"
                        value="{{form.contacto.value |default_if_none:"" }}" style="" type="text" maxlength="255">
                    </div>
                    <!---->
                  </div>
                </div>
                <hr>
              </div>



              {% if registo == 2 or registo == 3 %}

              <div class="columns">
                <div class="column">
                  <div class="field">
                    <label class="label">Faculdade</label>
                    <div class="control is-clearfix">

                      <div class="field">
                        <!---->
                        <div class="control is-expanded">
                          <span class="select is-fullwidth is-empty">
                            {{form.faculdade}}
                          </span>
                          <!---->
                        </div>
                        <!---->
                      </div>

                    </div>
                    <!---->
                  </div>
                </div>
                <div class="column">
                  <div class="field">
                    <label class="label">Departamento</label>
                    <div class="control is-clearfix">

                      <div class="field">
                        <!---->
                        <div class="control is-expanded">
                          <span class="select is-fullwidth is-empty">
                            {{form.departamento}}
                          </span>
                          <!---->
                        </div>
                        <!---->
                      </div>

                    </div>
                    <!---->
                  </div>
                </div>
                <div class="column">
                  <div class="field">
                    <label class="label">Gabinete</label>
                    <div class="control is-clearfix">
                      <input class="input" name="gabinete" id="id_gabinete"
                        value="{{form.gabinete.value|default_if_none:"" }}" type="text" style="" maxlength="255">
                    </div>
                    <!---->
                  </div>
                </div>
                <hr>
              </div>
              {% elif registo == 4%}


              <div class="columns">
                <div class="column">
                  <div class="field">
                    <label class="label">Faculdade</label>
                    <div class="control is-clearfix">

                      <div class="field">
                        <!---->
                        <div class="control is-expanded">
                          <span class="select is-fullwidth is-empty">
                            {{form.faculdade}}
                          </span>
                          <!---->
                        </div>
                        <!---->
                      </div>

                    </div>
                    <!---->
                  </div>
                </div>
                <div class="column">
                  <div class="field">
                    <label class="label">Departamento</label>
                    <div class="control is-clearfix">

                      <div class="field">
                        <!---->
                        <div class="control is-expanded">
                          <span class="select is-fullwidth is-empty">
                            {{form.departamento}}
                          </span>
                          <!---->
                        </div>
                        <!---->
                      </div>

                    </div>
                    <!---->
                  </div>
                </div>
                <div class="column">
                  <div class="field">
                    <label class="label">Curso</label>
                    <div class="control is-clearfix">

                      <div class="field">
                        <!---->
                        <div class="control is-expanded">
                          <span class="select is-fullwidth is-empty">
                            {{form.curso}}
                          </span>
                          <!---->
                        </div>
                        <!---->
                      </div>

                    </div>
                    <!---->
                  </div>
                </div>
                <hr>
              </div>
              {% elif registo == 5%}

              <div class="columns" style="margin-right:66.6%;">
                <div class="column">
                  <div class="field">

                    <label class="label">Gabinete</label>
                    <div class="control is-clearfix">
                      <input class="input" name="gabinete" id="id_gabinete"
                        value="{{form.gabinete.value|default_if_none:"" }}" type="text" style="" maxlength="255">
                    </div>
                    <!---->
                  </div>
                </div>
                <hr>
              </div>
              {% endif %}
              <div style="margin-top:2%;text-align:center;position:center;">
                <a href="{% url 'utilizadores:consultar-utilizadores' %}" aria-current="page">
                <button type="button" value="Voltar" class="button is-outlined" style="margin-right:5%">Voltar</button>
                </a>

                {% if perfil == "Participante" %}
                <a
                  onclick="alert.render('<b>Atenção!</b><br><br>Ao alterar o perfil deste participante a sua <b>incrição</b> será apagada permanentemente.','{% url 'utilizadores:mudar-perfil-escolha-admin' id %}')">
                  {% elif perfil == "Colaborador" %}
                  <a
                    onclick="alert.render('<b>Atenção!</b><br><br>Ao alterar o perfil deste colaborador as suas <b>tarefas</b> deixarão de lhe estar atribuidas.','{% url 'utilizadores:mudar-perfil-escolha-admin' id %}')">
                    {% elif perfil == "Professor Universitario" %}
                    <a
                      onclick="alert.render('<b>Atenção!</b><br><br>Ao alterar o perfil deste professor universitário as suas <b>atividades</b> serão apagadas permanentemente.','{% url 'utilizadores:mudar-perfil-escolha-admin' id %}')">
                      {% elif  perfil == "Coordenador" %}
                      <a
                        onclick="alert.render('<b>Atenção!</b><br><br>Ao alterar o perfil deste coordenador as <b>atividades dos departamentos</b> pelo qual está responsável serão apagadas permanentemente.<br><br>As <b>tarefas dos colaboradores</b> pelo qual este coordenador está responsável serão apagadas permanentemente.','{% url 'utilizadores:mudar-perfil-escolha-admin' id %}')">
                        {% elif  perfil == "Administrador" %}
                        <a
                          onclick="alert.render('<b>Atenção!</b><br><br>Ao alterar o perfil deste administrador todas as suas <b>informações</b> serão apagadas frequentemente incluindo os <b>dados de configuração</b> do dia aberto pelo qual este administrador está responsável.','{% url 'utilizadores:mudar-perfil-escolha-admin' id %}')">
                          {% endif %}
                          <button type="button" class="button is-link is-outlined" style="margin-right:5%">Escolher
                            outro perfil</button>
                        </a>


                        <button style="" type="submit" class="button is-success is-outlined">
                          <span>Confirmar</span>
                        </button>
              </div>
        </form>




        {% if msg %}
        <div style="margin-left:30%;margin-right:30%; margin-top:%">
          <div style="margin-top:2%;text-align: center;position:center;">
            <article class="message is-danger">
              <div class="message-body">
                <p style="text-align: center;">
                  {% if form.non_field_errors %}
                  {% for error in form.non_field_errors %}
                  <p style="color: #ff0000; text-align:center">{{error}}</p>
                  {% endfor %}
                  {% endif %}
                  {% for error in erros %}
                  <p style="color: #ff0000; text-align:center">{{error}}</p>
                  {% endfor %}

                
                  {% for field in form %}
                  {% for error in field.errors %}
                  {% if field.name == "email" %}
                  <p style="color: #ff0000;">{{ error }}</p>
                  {% endif %}
                  {% endfor %}
                  {% endfor %}



                </p>
              </div>
            </article>
          </div>
        </div>
        {% endif %}
</div>
</div>
</div>

{% endblock content %}




{% block scripts %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>


  {% if registo == 2 %}
  $("#id_faculdade").change(function () {
    var url = $("#ProfessorUniversitarioRegisterForm").attr("data-departamentos-url");
    var faculdadeid = $(this).val();

    $.ajax({
      url: url,
      data: {
        'faculdade': faculdadeid
      },
      success: function (data) {
        $("#id_departamento").html(data);
      }
    });

  }); 
  {% elif registo == 3 %}
  $("#id_faculdade").change(function () {
    var url = $("#CoordenadorRegisterForm").attr("data-departamentos-url");
    var faculdadeid = $(this).val();

    $.ajax({
      url: url,
      data: {
        'faculdade': faculdadeid
      },
      success: function (data) {
        $("#id_departamento").html(data);
      }
    });

  }); 
  {% elif registo == 4 %}
  $("#id_faculdade").change(function () {

    var url = $("#ColaboradorRegisterForm").attr("data-cursos-url");
    var faculdadeid = $(this).val();

    $.ajax({
      url: url,
      data: {
        'faculdade': faculdadeid
      },
      success: function (data) {
        $("#id_curso").html(data);

      }
    });

  });
  $("#id_faculdade").change(function () {

    var url = $("#ColaboradorRegisterForm").attr("data-departamentos-url");
    var faculdadeid = $(this).val();

    $.ajax({
      url: url,
      data: {
        'faculdade': faculdadeid
      },
      success: function (data) {
        $("#id_departamento").html(data);

      }
    });

  }); {% endif %}
</script>
{% endblock scripts %}

src/Utilizadores/templates/utilizadores/curso_dropdown_list_options.html
<option value="">---------</option>
{% for curso in cursos %}
<option value="{{ curso.id }}">{{ curso.nome }}</option>
{% endfor %}