src/App/urls.py
from django.contrib import admin

from django.urls import include, path
from GestorTemplates.views import home
from django.views.i18n import JavaScriptCatalog


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('jsi18n', JavaScriptCatalog.as_view(), name='js-catlog'),
    path('Evento/', include('Evento.urls', namespace='Evento')),
    path('Utilizadores/', include('Utilizadores.urls', namespace='Utilizadores')),
    path('GestorTemplates/', include('GestorTemplates.urls')),
    path('Recurso/', include('Recurso.urls')),
    path('Inscricao/', include('Inscricao.urls')),
    path('Feedback/', include('Feedback.urls')),
    path('notificacoes/', include('Notificacoes.urls')),

]

src/Evento/urls.py
from django.urls import path
from .views import home_view, eventos, create_logistic, meus_eventos, gerir, select_type, create_event, \
    eventos_gerir, equip_logistic, espaco_logistic, servico_logistic, submit_logistic, view_logisticas, \
    view_event, ajax_filter_type, ajax_filter_state, delete_event, edit_event, ajax_finalizar_logistica, \
    validar_evento, delete_logistica, edit_logistica, edit_espaco, edit_servico, edit_equipamento, \
    select_form, submeter_event, aceitar_event, view_my_event, recusar_evento, evento_insc, associar_insc, \
    associar_feedback, evento_feedback

app_name = 'Evento'

urlpatterns = [
    path('', home_view, name='homeview'),
    path('all/', eventos, name='eventos'),
    path('myevents/', meus_eventos, name='meus-eventos'),
    path('gerir/<int:event_id>', gerir, name='gerir'),
    path('gerir/', eventos_gerir, name='eventos-gerir'),
    path('new/', select_type, name='select_type'),
    path('new/form/<int:type_id>', select_form, name='select_form'),
    path('new/create/<int:type_id>/<int:type_evento>', create_event, name='create-event'),
    path('new/submit/<int:event_id>', submeter_event, name='submeter-event'),
    path('new/aceitar/<int:event_id>', aceitar_event, name='aceitar-event'),
    path('new2/<int:event_id>', create_logistic, name='create-event2'),
    path('new2/equip/<int:event_id>', equip_logistic, name='equip-logistic'),
    path('new2/espaco/<int:event_id>', espaco_logistic, name='espaco-logistic'),
    path('new2/servico/<int:event_id>', servico_logistic, name='servico-logistic'),
    path('new2/submit_logistic/<int:event_id>', submit_logistic, name='submit-logistic'),
    path('gerir/view-logistic/<int:event_id>', view_logisticas, name='view-logistic'),
    path('gerir/validar-evento/<int:event_id>', validar_evento, name='validar-evento'),
    path('gerir/recusar-evento/<int:event_id>', recusar_evento, name='recusar-evento'),
    path('view/<int:event_id>', view_event, name='view-event'),
    path('view-my/<int:event_id>', view_my_event, name='view-my-event'),
    path('ajax/', ajax_filter_type, name='ajax-filter-type'),
    path('ajax/state', ajax_filter_state, name='ajax-filter-state'),
    path('ajax/finalizar_logistica', ajax_finalizar_logistica, name='ajax-finalizar-logistica'),
    path('delete/<int:event_id>', delete_event, name='delete-event'),
    path('delete-logistica/<int:event_id>', delete_logistica, name='delete-logistica'),
    path('edit/<int:event_id>', edit_event, name='edit-event'),
    path('edit-logistica/<int:event_id>', edit_logistica, name='edit-logistica'),
    path('edit-espaco/<int:event_id>', edit_espaco, name='edit-espaco'),
    path('edit-espaco/<int:event_id>/<int:espaco_id>/<str:tipo>', edit_espaco, name='edit-espaco'),
    path('edit-servico/<int:event_id>', edit_servico, name='edit-servico'),
    path('edit-equipamento/<int:event_id>', edit_equipamento, name='edit-equipamento'),

    path('evento-insc/<int:event_id>', evento_insc, name='evento-insc'),
    path('evento-feed/<int:event_id>', evento_feedback, name='evento-feed'),
    path('associar-insc/<int:event_id>/<int:form_id>', associar_insc, name='associar-insc'),
    path('associar-feedback/<int:event_id>/<int:form_id>', associar_feedback, name='associar-feedback'),
]

src/Inscricao/urls.py
from django.urls import path

import Inscricao.views
from .views import CriarInscricao, PartConsultarInscricoes, PartInscricaoCancelar,\
    PropAlterarEstadoInscricao, PropConsultarInscricoes, PropRemoverInscricao,  PartInscricaoCheckin,\
    PartAlterarInscricao,  returnCurrentEstado, updateEstado, PropConsultarCheckIns, doCheckin, PropAlterarInscricao, consultarInscricaoProp, consultarInscricaoPart,\
    create_csv_certificates, PropConsultarInscricoesFIX, PropConsultarCheckInsFIX, PropAlterarInscricaoFIX, PropRemoverInscricaoFIX, PropAlterarEstadoInscricaoFIX, consultarInscricaoPropFIX

app_name = 'Inscricao'

urlpatterns = [


    #PARA PROPONENTES FIX
    path('consultarpro/<int:eventoid>', PropConsultarInscricoesFIX.as_view(), name='prop_list_inscricao_FIX'),
    path('consultarCheckinspro/<int:eventoid>', PropConsultarCheckInsFIX.as_view(), name='consultar_checkins_FIX'),
    path('alterarpro/<int:id>', PropAlterarInscricaoFIX, name='prop_alterar_inscricao_FIX'),
    path('deletepro/<int:inscricaoid>', PropRemoverInscricaoFIX, name='prop_delete_inscricao_FIX'),
    path('alterarEstadopro/<int:id>', PropAlterarEstadoInscricaoFIX, name='prop_update_inscricao_fix'),
    path('consultarinscricaopro/<int:inscricaoid>', consultarInscricaoPropFIX, name='consultar_inscricao_prop_FIX'),


    # URL'S para os participantes
    path('create/<int:eventoid>/', CriarInscricao, name='create_inscricao'),
    path('', PartConsultarInscricoes.as_view(), name='part_list_inscricao'),
    path('evento/<int:eventoid>', PropConsultarInscricoes.as_view(), name='prop_list_inscricao'),
    path('delete/<int:inscricaoid>/', PartInscricaoCancelar, name='part_delete_inscricao'),
    path('evento/delete/<int:inscricaoid>/', PropRemoverInscricao, name='prop_delete_inscricao'),
    path('evento/update/<int:id>/', PropAlterarEstadoInscricao, name='prop_update_inscricao'),
    path('update/<int:id>/', PartInscricaoCheckin, name='part_update_inscricao'),
    path('alterar/<int:id>', PartAlterarInscricao, name='part_alterar_inscricao'),
    path('getInsEstado/<int:id>', returnCurrentEstado, name='get_ins_estado'),
    path('updateEstado/<int:id>', updateEstado ),
    path('checkIns/<int:eventoid>', PropConsultarCheckIns.as_view(), name='consultar_checkins' ),
    path('doCheckin/<int:id>', doCheckin),
    path('alterarProp/<int:id>', PropAlterarInscricao, name='prop_alterar_inscricao'),
    path('certificados/<int:evento_id>', create_csv_certificates, name='certificates_csv'),

    #URL'S para os proponentes


    #URL's para ambos
    path('consultar/<int:inscricaoid>', consultarInscricaoPart, name='consultar_inscricao_part'),
    path('consulta/<int:inscricaoid>', consultarInscricaoProp, name='consultar_inscricao_prop'),

]

src/Inscricao/views.py
import csv

from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.core import serializers
from GestorTemplates.models import Tipoformulario, Formulario, CampoFormulario, Campo, Resposta, EventoFormulario
from Notificacoes.models import Notificacao
from Utilizadores.models import User
from .forms import InscricaoForm, InscricaoUpdateForm, InscricaoCheckinUpdateForm
from Evento.models import Evento
from .models import Inscricao
from django.urls import reverse_lazy
from django.contrib import messages
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView
from datetime import date, datetime
from Feedback.models import Feedback
from django.contrib.auth import get_user_model
# -------- Views associadas ao perfl de PARTICIPANTES -----------------------------------------------------

# TODO : fazer uma outra versão para utilizadores autenticados
def CriarInscricao(request, eventoid):
    evento = Evento.objects.get(id=eventoid)

    if evento.inscritos == evento.maxparticipantes:
        messages.error(request, f'O número máximo de inscritos foi atingido.')

        return redirect('Evento:eventos')

    if evento.visibilidade == "Privado" and  not request.user.is_authenticated :
        messages.error(request, f"Precisa de estar logged in para se inscrever em eventos privados.")

    if request.user.is_authenticated :

        if Inscricao.objects.filter(eventoid=eventoid,email=request.user.email).exists():
            messages.error(request, f'Já se encontra inscrito neste evento!')
            return redirect('Evento:eventos')

        formularioEvento = EventoFormulario.objects.filter(eventoid=evento.id,
                                                           formularioid__tipoformularioid__categoria=1)

        formularioInscricao = formularioEvento[0].formularioid

        perguntas = CampoFormulario.objects.filter(formularioid=formularioInscricao.id,
                                                   campoid__campo_relacionado=None).exclude(campoid_id=28).exclude(
            campoid_id=27).exclude(campoid_id=1).exclude(campoid_id=2).exclude(campoid_id=3)

        for pergunta in perguntas:
            if (pergunta.campoid.tipocampoid.nome == "Escolha Múltipla" or
                    pergunta.campoid.tipocampoid.nome == 'Dropdown'):
                pergunta.campoid.respostas = Campo.objects.filter(campo_relacionado=pergunta.campoid)

    else :
        formularioEvento = EventoFormulario.objects.filter(eventoid=evento.id,
                                                           formularioid__tipoformularioid__categoria=1)

        formularioInscricao = formularioEvento[0].formularioid

        perguntas = CampoFormulario.objects.filter(formularioid=formularioInscricao.id,
                                                   campoid__campo_relacionado=None).exclude(campoid_id=28).exclude(
            campoid_id=27)

        for pergunta in perguntas:
            if (pergunta.campoid.tipocampoid.nome == "Escolha Múltipla" or
                    pergunta.campoid.tipocampoid.nome == 'Dropdown'):
                pergunta.campoid.respostas = Campo.objects.filter(campo_relacionado=pergunta.campoid)

    if request.method == 'POST':
        temp_email =  request.POST.get("3")
        if Inscricao.objects.filter(eventoid=eventoid,email=temp_email).exists():
            messages.error(request, f'Já existe uma inscrição com este email!')
            context = {
                'form': perguntas,
                'evento': evento,
            }
            return render(request, 'inscricao/participantes/inscricao_create.html', context)
        # TODO : Aqui deve acontecer alguma validação dos campos submetidos

        if request.user.is_authenticated:
            num_inscricao = evento.inscritos + 1

            evento.inscritos = evento.inscritos + 1
            evento.save()

            respostas = []

            inscricao = Inscricao(eventoid=evento)
            user_django = request.user
            user = User.objects.filter(email=user_django.email)[0]
            today = date.today()
            inscricao.idade = today.year - user.datanascimento.year
            inscricao.nome = f"{user.first_name} {user.last_name}"
            inscricao.email = user.email
            for pergunta in perguntas:
                perguntaid = pergunta.campoid.id
                # print(perguntaid)
                resposta = request.POST.get(f"{perguntaid}")
                if perguntaid == 4:  # NUMERO TELEMOVEL
                    inscricao.telemovel = resposta
                elif perguntaid == 5:  # PROFISSAO
                    inscricao.profissao = resposta
                respostas.append(Resposta(conteudo=resposta, inscricaoid=inscricao, campoid=pergunta.campoid))

            if evento.val_inscritos:
                estado = "Pendente"
            else:
                estado = "Válida"



            inscricao.eventoid = evento
            inscricao.userid = user

            inscricao.estado = estado
            respostas.append(Resposta(conteudo=estado, inscricaoid=inscricao, campoid=Campo.objects.get(id=27)))

            inscricao.num_inscricao = num_inscricao

            inscricao.checkin = 0
            respostas.append(Resposta(conteudo=0, inscricaoid=inscricao, campoid=Campo.objects.get(id=28)))

            inscricao.save()

            for resposta in respostas:
                resposta.save()

            messages.success(request, f'Concluiu a sua inscrição com sucesso!')

            return redirect('Evento:eventos')

        else:
            num_inscricao = evento.inscritos + 1

            evento.inscritos = evento.inscritos + 1
            evento.save()

            respostas = []

            inscricao = Inscricao(eventoid=evento)
            for pergunta in perguntas:
                perguntaid = pergunta.campoid.id
                # print(perguntaid)
                resposta = request.POST.get(f"{perguntaid}")
                # print(resposta)
                if perguntaid == 1:  # NOME
                    inscricao.nome = resposta
                elif perguntaid == 2:  # IDADE
                    print("im here")
                    inscricao.idade = resposta
                elif perguntaid == 3:  # EMAIL
                    inscricao.email = resposta
                elif perguntaid == 4:  # NUMERO TELEMOVEL
                    inscricao.telemovel = resposta
                elif perguntaid == 5:  # PROFISSAO
                    inscricao.profissao = resposta
                respostas.append(Resposta(conteudo=resposta, inscricaoid=inscricao, campoid=pergunta.campoid))

            if evento.val_inscritos:
                estado = "Pendente"
            else:
                estado = "Válida"


            userid = None

            inscricao.eventoid = evento
            inscricao.userid = userid

            inscricao.estado = estado
            respostas.append(Resposta(conteudo=estado, inscricaoid=inscricao, campoid=Campo.objects.get(id=27)))

            inscricao.num_inscricao = num_inscricao

            inscricao.checkin = 0
            respostas.append(Resposta(conteudo=0, inscricaoid=inscricao, campoid=Campo.objects.get(id=28)))

            inscricao.save()

            for resposta in respostas:
                resposta.save()

            messages.success(request, f'Concluiu a sua inscrição com sucesso!')

            return redirect('Evento:eventos')

    if len(perguntas) == 0:
        messages.success(request, f'Concluiu a sua inscrição com sucesso!')


        return redirect('Evento:eventos')

    context = {
        'form': perguntas,
        'evento' : evento,
    }
    return render(request, 'inscricao/participantes/inscricao_create.html', context)


# TODO: melhorar a consulta com filtros e barra de procura
class PartConsultarInscricoes(ListView):
    # We don't have users yet.
    # if not request.user.is_authenticated:
    #         messages.error(request, f'Por favor, faça login primeiro.')
    #         return redirect('Inscricao:list_inscricao')

    template_name = 'inscricao/participantes/list_inscricao2.html'

    paginate_by = 10

    def get_queryset(self):
        if self.request.user.is_authenticated:
            user_django = self.request.user
            user = User.objects.filter(email=user_django.email)
            realuser = user[0]
            # return Inscricao.objects.filter(userid=realuser.id)
            queryset = Inscricao.objects.filter(userid=realuser.id)
            for inscricao in queryset:
                today = datetime.today()
                eventoDataFinal = inscricao.eventoid.horario.datafinal
                eventoHoraFinal = inscricao.eventoid.horario.horafinal
                eventFinalDate = datetime.combine(eventoDataFinal,eventoHoraFinal)
                if eventFinalDate < today and EventoFormulario.objects.filter(eventoid=inscricao.eventoid, formularioid__tipoformularioid__categoria=2).exists() and not Feedback.objects.filter(eventoid=inscricao.eventoid, userid=realuser).exists() and Inscricao.objects.filter(eventoid=inscricao.eventoid, userid=realuser)[0].checkin :
                    inscricao.hasFeedback = True
            return queryset
        else:
            return None

    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated :
            messages.error(request, f'Por favor, faça login primeiro.')
            return redirect('Evento:eventos')
        return super(PartConsultarInscricoes, self).get(request,*args,**kwargs)

    # Show the inscricoes of the users
    # def get_queryset(self):
        # return Inscricao.objects.filter(userid=self.request.user)


# TODO : apenas para utilizadores logged in
def PartInscricaoCancelar(request, inscricaoid):
    # We don't have users yet.
    # if not request.user.is_authenticated:

src/templates/inscricao/inscricao_consultar.html
{% extends 'app.html' %}


{% block title %}- Página Inicial{% endblock title %}

{% block content %}
{% load static %}
<div>
  <div class="section">
    <div class="columns">
      <div class="column is-is-four-fifths">

                <div>
            <div class="section">
                <div class="columns is-align-items-center">
                    <div class="column">
                        <div class="img"></div>
                    </div>
                    <div class="column">
                        <h1 class="title has-text-centered"> Dados gerais da inscrição</h1>
                        {% for resposta in inscricao %}
                        <div class="event-group">
                            <span class="span-header">{{ resposta.campoid.conteudo }}</span>
                                <p class="event-body ">
                                    {% if resposta.conteudo|length == 0  %}Answer is empty.
                                {% elif resposta.campoid.id == 28 %} {% if  resposta.conteudo == "0" %} Check-in não confirmado. {% else %} Check-in confirmado. {% endif %}
                                {% else %} {{ resposta.conteudo }}  {% endif %}</p>
                        </div>
                          {% endfor %}

                    </div>
                </div>
            </div>
        </div>


            <div class="control">
                <a class="button is-link" href="{% url 'Inscricao:part_list_inscricao' %}"> Voltar atrás </a>
            </div>


    </div>
  </div>
 </div>
</div>
{% endblock content%}

src/templates/inscricao/inscricao_consultar_part.html
{% extends 'app.html' %}


{% block title %}- Página Inicial{% endblock title %}

{% block content %}
{% load static %}

          <div class="navbar-menu is-white" id="form-menu-buttons">
        <div class="navbar-start">
          <!-- navbar items on the left side -->
          <div class="column">
            <nav class="breadcrumb has-bullet-separator is-medium" aria-label="breadcrumbs">
              <ul>
                  <li><a href="{% url 'Inscricao:part_list_inscricao'  %}">As minhas inscrições</a></li>
                <li class="is-active">
                  <a href="#" aria-current="page">
                    <span class="has-text-weight-bold">Consultar inscrição</span>
                  </a>
                </li>
              </ul>
            </nav>
          </div>
        </div>
      </div>


<div>
  <div class="section">
    <div class="columns">
      <div class="column is-is-four-fifths">

                <div>
            <div class="section">
                <div class="columns is-align-items-center">
                    <div class="column">
                        <div class="img"></div>
                    </div>
                    <div class="column">
                        <h1 class="title has-text-centered"> Dados gerais da inscrição</h1>
                        {% for resposta in inscricao %}
                        <div class="event-group">
                            <span class="span-header">{{ resposta.campoid.conteudo }}</span>
                                <p class="event-body ">
                                    {% if resposta.conteudo|length == 0  %}Answer is empty.
                                {% elif resposta.campoid.id == 28 %} {% if  resposta.conteudo == "0" %} Check-in não confirmado. {% else %} Check-in confirmado. {% endif %}
                                {% else %} {{ resposta.conteudo }}  {% endif %}</p>
                        </div>
                          {% endfor %}

                    </div>
                </div>
            </div>
        </div>


            <div class="control">
                <a class="button is-link" href="{% url 'Inscricao:part_list_inscricao' %}"> Voltar atrás </a>
            </div>


    </div>
  </div>
 </div>
</div>
{% endblock content%}

src/templates/inscricao/inscricao_consultar_prop.html
{% extends 'app.html' %}


{% block title %}- Página Inicial{% endblock title %}

{% block content %}
{% load static %}

          <div class="navbar-menu is-white" id="form-menu-buttons">
        <div class="navbar-start">
          <!-- navbar items on the left side -->
          <div class="column">
            <nav class="breadcrumb has-bullet-separator is-medium" aria-label="breadcrumbs">
              <ul>
                   {% if not fix %}
                  <li><a href="{% url 'Evento:eventos-gerir'  %}">Eventos a gerir</a></li>
                  <li><a href="{% url 'Evento:gerir' event_id=evento.id %}">Gerir evento</a></li>
                  <li><a href="{% url 'Inscricao:prop_list_inscricao' eventoid=evento.id %}">Inscrições do evento</a></li>
                  {% else %}
                    <li><a href="{% url 'Evento:meus-eventos'  %}">Meus eventos</a></li>
                  <li><a href="{% url 'Inscricao:prop_list_inscricao' eventoid=evento.id %}">Inscrições do evento</a></li>
                  {% endif %}
                <li class="is-active">
                  <a href="#" aria-current="page">
                    <span class="has-text-weight-bold">Consultar inscrição</span>
                  </a>
                </li>
              </ul>
            </nav>
          </div>
        </div>
      </div>



<div>
  <div class="section">
    <div class="columns">
      <div class="column is-is-four-fifths">

                <div>
            <div class="section">
                <div class="columns is-align-items-center">
                    <div class="column">
                        <div class="img"></div>
                    </div>
                    <div class="column">
                        <h1 class="title has-text-centered"> Dados gerais da inscrição</h1>
                        {% for resposta in inscricao %}
                        <div class="event-group">
                            <span class="span-header">{{ resposta.campoid.conteudo }}</span>
                                <p class="event-body ">
                                    {% if resposta.conteudo|length == 0  %}Answer is empty.
                                {% elif resposta.campoid.id == 28 %} {% if  resposta.conteudo == "0" %} Check-in não confirmado. {% else %} Check-in confirmado. {% endif %}
                                {% else %} {{ resposta.conteudo }}  {% endif %}</p>
                        </div>
                          {% endfor %}

                    </div>
                </div>
            </div>
        </div>


            <div class="control">
                {% if not fix %}
                <a class="button is-link" href="{% url 'Inscricao:prop_list_inscricao' eventoid=evento.id %}"> Voltar atrás </a>
                {% else %}
                <a class="button is-link" href="{% url 'Inscricao:prop_list_inscricao_FIX' eventoid=evento.id %}"> Voltar atrás </a>

                {% endif %}
            </div>


    </div>
  </div>
 </div>
</div>
{% endblock content%}