src/App/urls.py
from django.contrib import admin

from django.urls import include, path
from GestorTemplates.views import home
from django.views.i18n import JavaScriptCatalog


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('jsi18n', JavaScriptCatalog.as_view(), name='js-catlog'),
    path('Evento/', include('Evento.urls', namespace='Evento')),
    path('Utilizadores/', include('Utilizadores.urls', namespace='Utilizadores')),
    path('GestorTemplates/', include('GestorTemplates.urls')),
    path('Recurso/', include('Recurso.urls')),
    path('Inscricao/', include('Inscricao.urls')),
    path('Feedback/', include('Feedback.urls')),
    path('notificacoes/', include('Notificacoes.urls')),

]

src/Evento/urls.py
from django.urls import path
from .views import home_view, eventos, create_logistic, meus_eventos, gerir, select_type, create_event, \
    eventos_gerir, equip_logistic, espaco_logistic, servico_logistic, submit_logistic, view_logisticas, \
    view_event, ajax_filter_type, ajax_filter_state, delete_event, edit_event, ajax_finalizar_logistica, \
    validar_evento, delete_logistica, edit_logistica, edit_espaco, edit_servico, edit_equipamento, \
    select_form, submeter_event, aceitar_event, view_my_event, recusar_evento, evento_insc, associar_insc, \
    associar_feedback, evento_feedback

app_name = 'Evento'

urlpatterns = [
    path('', home_view, name='homeview'),
    path('all/', eventos, name='eventos'),
    path('myevents/', meus_eventos, name='meus-eventos'),
    path('gerir/<int:event_id>', gerir, name='gerir'),
    path('gerir/', eventos_gerir, name='eventos-gerir'),
    path('new/', select_type, name='select_type'),
    path('new/form/<int:type_id>', select_form, name='select_form'),
    path('new/create/<int:type_id>/<int:type_evento>', create_event, name='create-event'),
    path('new/submit/<int:event_id>', submeter_event, name='submeter-event'),
    path('new/aceitar/<int:event_id>', aceitar_event, name='aceitar-event'),
    path('new2/<int:event_id>', create_logistic, name='create-event2'),
    path('new2/equip/<int:event_id>', equip_logistic, name='equip-logistic'),
    path('new2/espaco/<int:event_id>', espaco_logistic, name='espaco-logistic'),
    path('new2/servico/<int:event_id>', servico_logistic, name='servico-logistic'),
    path('new2/submit_logistic/<int:event_id>', submit_logistic, name='submit-logistic'),
    path('gerir/view-logistic/<int:event_id>', view_logisticas, name='view-logistic'),
    path('gerir/validar-evento/<int:event_id>', validar_evento, name='validar-evento'),
    path('gerir/recusar-evento/<int:event_id>', recusar_evento, name='recusar-evento'),
    path('view/<int:event_id>', view_event, name='view-event'),
    path('view-my/<int:event_id>', view_my_event, name='view-my-event'),
    path('ajax/', ajax_filter_type, name='ajax-filter-type'),
    path('ajax/state', ajax_filter_state, name='ajax-filter-state'),
    path('ajax/finalizar_logistica', ajax_finalizar_logistica, name='ajax-finalizar-logistica'),
    path('delete/<int:event_id>', delete_event, name='delete-event'),
    path('delete-logistica/<int:event_id>', delete_logistica, name='delete-logistica'),
    path('edit/<int:event_id>', edit_event, name='edit-event'),
    path('edit-logistica/<int:event_id>', edit_logistica, name='edit-logistica'),
    path('edit-espaco/<int:event_id>', edit_espaco, name='edit-espaco'),
    path('edit-espaco/<int:event_id>/<int:espaco_id>/<str:tipo>', edit_espaco, name='edit-espaco'),
    path('edit-servico/<int:event_id>', edit_servico, name='edit-servico'),
    path('edit-equipamento/<int:event_id>', edit_equipamento, name='edit-equipamento'),

    path('evento-insc/<int:event_id>', evento_insc, name='evento-insc'),
    path('evento-feed/<int:event_id>', evento_feedback, name='evento-feed'),
    path('associar-insc/<int:event_id>/<int:form_id>', associar_insc, name='associar-insc'),
    path('associar-feedback/<int:event_id>/<int:form_id>', associar_feedback, name='associar-feedback'),
]

src/Inscricao/urls.py
from django.urls import path

import Inscricao.views
from .views import CriarInscricao, PartConsultarInscricoes, PartInscricaoCancelar,\
    PropAlterarEstadoInscricao, PropConsultarInscricoes, PropRemoverInscricao,  PartInscricaoCheckin,\
    PartAlterarInscricao,  returnCurrentEstado, updateEstado, PropConsultarCheckIns, doCheckin, PropAlterarInscricao, consultarInscricaoProp, consultarInscricaoPart,\
    create_csv_certificates, PropConsultarInscricoesFIX, PropConsultarCheckInsFIX, PropAlterarInscricaoFIX, PropRemoverInscricaoFIX, PropAlterarEstadoInscricaoFIX, consultarInscricaoPropFIX

app_name = 'Inscricao'

urlpatterns = [


    #PARA PROPONENTES FIX
    path('consultarpro/<int:eventoid>', PropConsultarInscricoesFIX.as_view(), name='prop_list_inscricao_FIX'),
    path('consultarCheckinspro/<int:eventoid>', PropConsultarCheckInsFIX.as_view(), name='consultar_checkins_FIX'),
    path('alterarpro/<int:id>', PropAlterarInscricaoFIX, name='prop_alterar_inscricao_FIX'),
    path('deletepro/<int:inscricaoid>', PropRemoverInscricaoFIX, name='prop_delete_inscricao_FIX'),
    path('alterarEstadopro/<int:id>', PropAlterarEstadoInscricaoFIX, name='prop_update_inscricao_fix'),
    path('consultarinscricaopro/<int:inscricaoid>', consultarInscricaoPropFIX, name='consultar_inscricao_prop_FIX'),


    # URL'S para os participantes
    path('create/<int:eventoid>/', CriarInscricao, name='create_inscricao'),
    path('', PartConsultarInscricoes.as_view(), name='part_list_inscricao'),
    path('evento/<int:eventoid>', PropConsultarInscricoes.as_view(), name='prop_list_inscricao'),
    path('delete/<int:inscricaoid>/', PartInscricaoCancelar, name='part_delete_inscricao'),
    path('evento/delete/<int:inscricaoid>/', PropRemoverInscricao, name='prop_delete_inscricao'),
    path('evento/update/<int:id>/', PropAlterarEstadoInscricao, name='prop_update_inscricao'),
    path('update/<int:id>/', PartInscricaoCheckin, name='part_update_inscricao'),
    path('alterar/<int:id>', PartAlterarInscricao, name='part_alterar_inscricao'),
    path('getInsEstado/<int:id>', returnCurrentEstado, name='get_ins_estado'),
    path('updateEstado/<int:id>', updateEstado ),
    path('checkIns/<int:eventoid>', PropConsultarCheckIns.as_view(), name='consultar_checkins' ),
    path('doCheckin/<int:id>', doCheckin),
    path('alterarProp/<int:id>', PropAlterarInscricao, name='prop_alterar_inscricao'),
    path('certificados/<int:evento_id>', create_csv_certificates, name='certificates_csv'),

    #URL'S para os proponentes


    #URL's para ambos
    path('consultar/<int:inscricaoid>', consultarInscricaoPart, name='consultar_inscricao_part'),
    path('consulta/<int:inscricaoid>', consultarInscricaoProp, name='consultar_inscricao_prop'),

]

src/Inscricao/views.py
import csv

from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.core import serializers
from GestorTemplates.models import Tipoformulario, Formulario, CampoFormulario, Campo, Resposta, EventoFormulario
from Notificacoes.models import Notificacao
from Utilizadores.models import User
from .forms import InscricaoForm, InscricaoUpdateForm, InscricaoCheckinUpdateForm
from Evento.models import Evento
from .models import Inscricao
from django.urls import reverse_lazy
from django.contrib import messages
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView
from datetime import date, datetime
from Feedback.models import Feedback
from django.contrib.auth import get_user_model
# -------- Views associadas ao perfl de PARTICIPANTES -----------------------------------------------------

# TODO : fazer uma outra versão para utilizadores autenticados
def CriarInscricao(request, eventoid):
    evento = Evento.objects.get(id=eventoid)

    if evento.inscritos == evento.maxparticipantes:
        messages.error(request, f'O número máximo de inscritos foi atingido.')

        return redirect('Evento:eventos')

    if evento.visibilidade == "Privado" and  not request.user.is_authenticated :
        messages.error(request, f"Precisa de estar logged in para se inscrever em eventos privados.")

    if request.user.is_authenticated :

        if Inscricao.objects.filter(eventoid=eventoid,email=request.user.email).exists():
            messages.error(request, f'Já se encontra inscrito neste evento!')
            return redirect('Evento:eventos')

        formularioEvento = EventoFormulario.objects.filter(eventoid=evento.id,
                                                           formularioid__tipoformularioid__categoria=1)

        formularioInscricao = formularioEvento[0].formularioid

        perguntas = CampoFormulario.objects.filter(formularioid=formularioInscricao.id,
                                                   campoid__campo_relacionado=None).exclude(campoid_id=28).exclude(
            campoid_id=27).exclude(campoid_id=1).exclude(campoid_id=2).exclude(campoid_id=3)

        for pergunta in perguntas:
            if (pergunta.campoid.tipocampoid.nome == "Escolha Múltipla" or
                    pergunta.campoid.tipocampoid.nome == 'Dropdown'):
                pergunta.campoid.respostas = Campo.objects.filter(campo_relacionado=pergunta.campoid)

    else :
        formularioEvento = EventoFormulario.objects.filter(eventoid=evento.id,
                                                           formularioid__tipoformularioid__categoria=1)

        formularioInscricao = formularioEvento[0].formularioid

        perguntas = CampoFormulario.objects.filter(formularioid=formularioInscricao.id,
                                                   campoid__campo_relacionado=None).exclude(campoid_id=28).exclude(
            campoid_id=27)

        for pergunta in perguntas:
            if (pergunta.campoid.tipocampoid.nome == "Escolha Múltipla" or
                    pergunta.campoid.tipocampoid.nome == 'Dropdown'):
                pergunta.campoid.respostas = Campo.objects.filter(campo_relacionado=pergunta.campoid)

    if request.method == 'POST':
        temp_email =  request.POST.get("3")
        if Inscricao.objects.filter(eventoid=eventoid,email=temp_email).exists():
            messages.error(request, f'Já existe uma inscrição com este email!')
            context = {
                'form': perguntas,
                'evento': evento,
            }
            return render(request, 'inscricao/participantes/inscricao_create.html', context)
        # TODO : Aqui deve acontecer alguma validação dos campos submetidos

        if request.user.is_authenticated:
            num_inscricao = evento.inscritos + 1

            evento.inscritos = evento.inscritos + 1
            evento.save()

            respostas = []

            inscricao = Inscricao(eventoid=evento)
            user_django = request.user
            user = User.objects.filter(email=user_django.email)[0]
            today = date.today()
            inscricao.idade = today.year - user.datanascimento.year
            inscricao.nome = f"{user.first_name} {user.last_name}"
            inscricao.email = user.email
            for pergunta in perguntas:
                perguntaid = pergunta.campoid.id
                # print(perguntaid)
                resposta = request.POST.get(f"{perguntaid}")
                if perguntaid == 4:  # NUMERO TELEMOVEL
                    inscricao.telemovel = resposta
                elif perguntaid == 5:  # PROFISSAO
                    inscricao.profissao = resposta
                respostas.append(Resposta(conteudo=resposta, inscricaoid=inscricao, campoid=pergunta.campoid))

            if evento.val_inscritos:
                estado = "Pendente"
            else:
                estado = "Válida"



            inscricao.eventoid = evento
            inscricao.userid = user

            inscricao.estado = estado
            respostas.append(Resposta(conteudo=estado, inscricaoid=inscricao, campoid=Campo.objects.get(id=27)))

            inscricao.num_inscricao = num_inscricao

            inscricao.checkin = 0
            respostas.append(Resposta(conteudo=0, inscricaoid=inscricao, campoid=Campo.objects.get(id=28)))

            inscricao.save()

            for resposta in respostas:
                resposta.save()

            messages.success(request, f'Concluiu a sua inscrição com sucesso!')

            return redirect('Evento:eventos')

        else:
            num_inscricao = evento.inscritos + 1

            evento.inscritos = evento.inscritos + 1
            evento.save()

            respostas = []

            inscricao = Inscricao(eventoid=evento)
            for pergunta in perguntas:
                perguntaid = pergunta.campoid.id
                # print(perguntaid)
                resposta = request.POST.get(f"{perguntaid}")
                # print(resposta)
                if perguntaid == 1:  # NOME
                    inscricao.nome = resposta
                elif perguntaid == 2:  # IDADE
                    print("im here")
                    inscricao.idade = resposta
                elif perguntaid == 3:  # EMAIL
                    inscricao.email = resposta
                elif perguntaid == 4:  # NUMERO TELEMOVEL
                    inscricao.telemovel = resposta
                elif perguntaid == 5:  # PROFISSAO
                    inscricao.profissao = resposta
                respostas.append(Resposta(conteudo=resposta, inscricaoid=inscricao, campoid=pergunta.campoid))

            if evento.val_inscritos:
                estado = "Pendente"
            else:
                estado = "Válida"


            userid = None

            inscricao.eventoid = evento
            inscricao.userid = userid

            inscricao.estado = estado
            respostas.append(Resposta(conteudo=estado, inscricaoid=inscricao, campoid=Campo.objects.get(id=27)))

            inscricao.num_inscricao = num_inscricao

            inscricao.checkin = 0
            respostas.append(Resposta(conteudo=0, inscricaoid=inscricao, campoid=Campo.objects.get(id=28)))

            inscricao.save()

            for resposta in respostas:
                resposta.save()

            messages.success(request, f'Concluiu a sua inscrição com sucesso!')

            return redirect('Evento:eventos')

    if len(perguntas) == 0:
        messages.success(request, f'Concluiu a sua inscrição com sucesso!')


        return redirect('Evento:eventos')

    context = {
        'form': perguntas,
        'evento' : evento,
    }
    return render(request, 'inscricao/participantes/inscricao_create.html', context)


# TODO: melhorar a consulta com filtros e barra de procura
class PartConsultarInscricoes(ListView):
    # We don't have users yet.
    # if not request.user.is_authenticated:
    #         messages.error(request, f'Por favor, faça login primeiro.')
    #         return redirect('Inscricao:list_inscricao')

    template_name = 'inscricao/participantes/list_inscricao2.html'

    paginate_by = 10

    def get_queryset(self):
        if self.request.user.is_authenticated:
            user_django = self.request.user
            user = User.objects.filter(email=user_django.email)
            realuser = user[0]
            # return Inscricao.objects.filter(userid=realuser.id)
            queryset = Inscricao.objects.filter(userid=realuser.id)
            for inscricao in queryset:
                today = datetime.today()
                eventoDataFinal = inscricao.eventoid.horario.datafinal
                eventoHoraFinal = inscricao.eventoid.horario.horafinal
                eventFinalDate = datetime.combine(eventoDataFinal,eventoHoraFinal)
                if eventFinalDate < today and EventoFormulario.objects.filter(eventoid=inscricao.eventoid, formularioid__tipoformularioid__categoria=2).exists() and not Feedback.objects.filter(eventoid=inscricao.eventoid, userid=realuser).exists() and Inscricao.objects.filter(eventoid=inscricao.eventoid, userid=realuser)[0].checkin :
                    inscricao.hasFeedback = True
            return queryset
        else:
            return None

    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated :
            messages.error(request, f'Por favor, faça login primeiro.')
            return redirect('Evento:eventos')
        return super(PartConsultarInscricoes, self).get(request,*args,**kwargs)

    # Show the inscricoes of the users
    # def get_queryset(self):
        # return Inscricao.objects.filter(userid=self.request.user)


# TODO : apenas para utilizadores logged in
def PartInscricaoCancelar(request, inscricaoid):
    # We don't have users yet.
    # if not request.user.is_authenticated:

src/templates/inscricao/gcp/list_inscricao2.html
{% extends 'app.html' %}

{% block title %}- Página Inicial{% endblock title %}


{% block page_css %}
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/dataTables.bulma.min.css">
<link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">

{% endblock %}
{% block content %}
{% load static %}
<div>
  <section  id="subnavbar" >
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a role="button" class="navbar-burger burger" onclick="$('#form-menu-buttons').toggleClass('is-active')">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
      <div class="navbar-menu is-white" id="form-menu-buttons">
        <div class="navbar-start">
          <!-- navbar items on the left side -->
          <div class="column">
            <nav class="breadcrumb has-bullet-separator is-medium" aria-label="breadcrumbs">
              <ul>
                  {% if not fix %}
                <li><a href="{% url 'Evento:eventos-gerir'  %}">Eventos a gerir</a></li>
                <li><a href="{% url 'Evento:gerir' event_id=request.resolver_match.kwargs.eventoid %}">Gerir evento</a></li>
                  {% else %}
                <li><a href="{% url 'Evento:meus-eventos'  %}">Meus eventos</a></li>
                  {% endif %}
                <li class="is-active">
                  <a href="#" aria-current="page">
                    <span class="has-text-weight-bold">Inscricões do evento</span>
                  </a>
                </li>
              </ul>
            </nav>
          </div>
        </div>
      </div>

    </nav>
    <div class="columns">
      <div class="column">
        <div class="tabs is-centered is-medium">
          <ul>
            <li class="is-active" data-column="0" data-filter="">
              <a>
                <span class="icon is-small"><i class="fas fa-file-invoice" aria-hidden="true"></i></span>
                <span>Todas</span>
              </a>
            </li>
            <li data-column="0" data-filter="Pendente">
              <a>
                <span class="icon is-small"><i class="ri-time-line " aria-hidden="true"></i></span>
                <span>Pendentes</span>
              </a>
            </li>
            <li data-column="0" data-filter="Inválida">
              <a>
                <span class="icon is-small"><i class="fas fa-times" aria-hidden="true"></i></span>
                <span>Invalidadas</span>
              </a>
            </li>
            <li data-column="0" data-filter="Válida">
              <a>
                <span class="icon is-small"><i class="fas fa-check" aria-hidden="true"></i></span>
                <span>Validadas</span>
              </a>
            </li>
            
          </ul>
      </div>
      </div>   
  </div>
  </section>

  <div class="section" id="main-section-content">
    <div class="columns">
      <div class="column ">

        <table id="form-list-table" class="table is-fullwidth is-striped is-hoverable" style="width:100%">
          <thead>
            <tr>
              <th>estado</th>
              <th>Nome</th>
              <th>Email</th>
              <th>Telemóvel</th>
              <th>Idade</th>
              <th>Profissão</th>
                <th> Estado</th>
              <th></th>

            </tr>
          </thead>
          <tbody>
            {% for obj in object_list %}
            <tr class="datatable-row datatable-selector" data-id="{{obj.pk}}">
              <td>{{obj.estado}}</td>
              <td> {{obj.nome}}</td>
              <td> {{obj.email}}</td>
              <td> {{obj.telemovel}}</td>
              <td> {{obj.idade}}</td>
              <td> {{obj.profissao}}</td>
{#                <td> {{ obj.estado }}</td>#}
                <td class="td-flex"> {% if obj.estado == "Inválida" %}<span class="ins-detail-red"> {{ obj.estado }}
                     {% elif obj.estado == "Válida" %}<span class="ins-detail-green"> {{ obj.estado }}
                    {% else %} <span class="ins-detail-yellow">{{ obj.estado }}
                    {% endif %}</span>
                </td>
              <td>
                  {% if not fix %}

                      <button class="button is-text has-text-grey ver_form_config has-tooltip-bottom validate-ins-btn"  data-update-url="{% url 'Inscricao:prop_alterar_inscricao' obj.pk %}" data-tooltip="Validar Inscrição: {{obj.nome}}">
                      <span class="icon">
                        <i class="fas fa-check" ></i>
                      </span>
                    </button>
                    <button class="button is-text has-text-grey ver_form_config has-tooltip-bottom update-ins-btn"  data-update-url="{% url 'Inscricao:prop_alterar_inscricao' obj.pk %}" data-tooltip="Alterar Inscrição: {{obj.nome}}">
                      <span class="icon">
                        <i class="far fa-edit" ></i>
                      </span>
                    </button>
                    <button class="button is-text has-text-grey ver_form_config has-tooltip-bottom delete-ins-btn"  data-delete-url="{% url 'Inscricao:prop_delete_inscricao' obj.pk %}" data-tooltip="Eliminar Inscrição: {{obj.nome}}">
                      <span class="icon">
                        <i class="far fa-trash-alt"></i>
                      </span>
                    </button>
                  {% else  %}
                                        <button class="button is-text has-text-grey ver_form_config has-tooltip-bottom validate-ins-btn"  data-update-url="{% url 'Inscricao:prop_alterar_inscricao_FIX' obj.pk %}" data-tooltip="Validar Inscrição: {{obj.nome}}">
                      <span class="icon">
                        <i class="fas fa-check" ></i>
                      </span>
                    </button>
                    <button class="button is-text has-text-grey ver_form_config has-tooltip-bottom update-ins-btn"  data-update-url="{% url 'Inscricao:prop_alterar_inscricao_FIX' obj.pk %}" data-tooltip="Alterar Inscrição: {{obj.nome}}">
                      <span class="icon">
                        <i class="far fa-edit" ></i>
                      </span>
                    </button>
                    <button class="button is-text has-text-grey ver_form_config has-tooltip-bottom delete-ins-btn"  data-delete-url="{% url 'Inscricao:prop_delete_inscricao_FIX' obj.pk %}" data-tooltip="Eliminar Inscrição: {{obj.nome}}">
                      <span class="icon">
                        <i class="far fa-trash-alt"></i>
                      </span>
                    </button>

                  {% endif %}

              </td>
            </tr>
            {% endfor %}
          </tbody>

        </table>
      </div>
    </div>
  </div>


</div>

<div class="modal" id="confirm-delete-form-modal" data-id="">
  <div class="modal-background"></div>
  <div class="modal-card">
    <header class="modal-card-head">
      <p class="modal-card-title">Tem a certeza que deseja eliminar esta inscrição ?</p>
      <button class="close-modal delete" aria-label="close"></button>
    </header>
    <section class="modal-card-body">
      <!-- Content ... -->
    </section>
    <footer class="modal-card-foot">
      <a class="button is-danger confirm" href="#">Eliminar</a>
      <button class="button close-modal">Cancelar</button>
    </footer>
  </div>
</div>


<div class="modal" id="validate_modal" data-id="">
  <div class="modal-background"></div>
  <div class="modal-card">
    <header class="modal-card-head">
      <p class="modal-card-title">Validação da inscrição</p>
      <button class="close-modal delete" aria-label="close"></button>
    </header>
    <section class="modal-card-body">
     <div class="field">
        <label class="field" for="{{ 27}}"> Escolha um dos três estados : </label>
            <div class="select is-small">
              <select name="{{ 27 }}" id="estado" >
                      <option name="Pendente"  > Pendente </option>
                      <option name="Válida"  > Válida </option>
                      <option name="Inválida"  > Inválida </option>
              </select>
            </div>
        </div>
    </section>
    <div class="field">

    <footer class="modal-card-foot">
      <a class="button is-success btn-confirm" href="#">Confirmar</a>
      <button class="button close-modal">Cancelar</button>
    </footer>
  </div>
</div>
</div>



{% endblock content%}

{% block scripts %}

<script type="text/javascript" src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.24/js/dataTables.bulma.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bulma-accordion@2.0.1/dist/js/bulma-accordion.min.js"></script>
<script>

  $('.dropdown').click(function () {
    $(this).toggleClass('is-active')
  });

  // ************ UPDATE INSCRICAO ******************8

  var updateInsBitton = $('.update-ins-btn');
updateInsBitton.click(function (e) {
    e.stopPropagation();
    location.href= $(this).data('update-url');
});

  // ************ VALIDATE INSCRICAO ******************8

  var validateFormModal = $('#validate_modal');

  $('.validate-ins-btn').click(function (e) {
      e.stopPropagation();
            validate_btn = $(this)
            console.log(validate_btn)
            let id = validate_btn.parent().parent().data('id')
          {#console.log(id);#}
            $.ajax({
                 url :`/Inscricao/getInsEstado/${id}`,
                type: "GET",
                beforeSend: function (xhr) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
                 },
                success: function (data) {
                    let estado = data['estado'];
                    {#console.log(estado);#}
                    {#console.log($(`option[name=${estado}]`));#}
                    $(`option[name=${estado}]`).attr("selected", "selected");
                    validateFormModal.addClass('is-active'); //shows modal
                    validateFormModal.attr('data-id', id)
                },
                error: function (error) {
                {#console.log(error);#}
                }

            })

    //todo add warning when deleting templates
  });


     function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    const csrftoken = getCookie('csrftoken');


      $('.btn-confirm').click(function (e)
      {
          {#console.log(e)#}
     const selected = document.querySelector("#estado").value;
    e.stopPropagation(); //para a propagacao do evento javascript
          confirm_btn = $(this)
          {#console.log(confirm_btn.parent().parent().parent().parent());#}
          let id = confirm_btn.parent().parent().parent().parent().data('id')
      console.log(id);
        $.ajax({
             url :`/Inscricao/updateEstado/${id}`,
            type: "POST",
            dataType: 'json',
            data: {
                selectedEstado: selected
            },
            beforeSend: function (xhr) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
             },
            success: function (data) {
                validateFormModal.removeClass('is-active'); //shows modal
                location.reload();
            },
            error: function (error) {
            console.log(error);
            }

        })

  })

  // *************** DELETE INCRICAO ***************
  var deleteFormModal = $('#confirm-delete-form-modal');
  $('.delete-ins-btn').click(function (e) {
    e.stopPropagation(); //para a propagacao do evento javascript 
    deleteFormModal.find('.confirm').attr('href', $(this).data('delete-url')); //passes obj id to modal
    deleteFormModal.addClass('is-active'); //shows modal
    //todo add warning when deleting templates
  });

  $('.close-modal').click(function () {
    $('.modal').removeClass('is-active');
  });


//DATATABLES MANIPULATION

    var table = $('#form-list-table').DataTable({
      "language": {
        "url": "//cdn.datatables.net/plug-ins/1.10.24/i18n/Portuguese.json"
      },
      "columnDefs": [ { "orderable": false, "targets": 7 },
      {
                "targets": [ 0 ],
                "visible": false
            }
    ],
    });

  $(document).ready(function () {

    //tabs filters
    let tabs = $('.tabs li')
    tabs.click(function(){
      tabs.removeClass('is-active')
      $(this).addClass('is-active');
      {#console.log(table.column($(this).data('column')).search($(this).data('filter')).draw())#}
      table.column($(this).data('column'))
        .search($(this).data('filter'))
        .draw();
    })
  });



  $('.datatable-row').click(function () {
    let url = "{% url 'Inscricao:consultar_inscricao_prop_FIX' inscricaoid=123  %}"
    location.href= url.replace('123',  $(this).data('id'))

  });


</script>
{% endblock %}